import Header from '@/components/header/Header'
import { Head } from 'next/document'
import { Fira_Sans, Rubik } from 'next/font/google'
import '@/scss/main.scss'

const firaSans = Fira_Sans({
	weight: ['400', '500'],
	subsets: ['cyrillic'],
	variable: '--font-fira-sans',
	display: 'swap'
})

const rubik = Rubik({
	weight: ['400', '500'],
	subsets: ['cyrillic'],
	variable: '--font-rubik',
	display: 'swap'
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en' className={`${firaSans.variable} ${rubik.variable}`}>
			<body>
				<Header />
				{children}
			</body>
		</html>
	)
}
